# Generated by Django 5.0.6 on 2024-05-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=255)),
                ('duriation', models.CharField(max_length=20)),
                ('parking_status', models.CharField(max_length=25)),
                ('parking_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('book_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(auto_now=True)),
                ('account_bal', models.DecimalField(decimal_places=2, default=20, max_digits=1000000)),
            ],
        ),
    ]
